### ISSUE TITLE
loading issues

### ISSUE THREAD

**Issue by joshpitzalis** [plastic-cup/polagraph#8]
ran npm install and then got the following error when we tried to run server.js

![screen shot 2015-06-17 at 15 47 03](https://cloud.githubusercontent.com/assets/10258114/8210096/61328218-1508-11e5-82ec-ea4c2a466130.png)

There is a typo in the package json. We fixed it and have submitted a pull request.

**Comment by SimonLab** [comment]
The same on ubuntu

**Comment by joshpitzalis** [comment]
fixed it on the fork and now its says  Cannot find module 'xml2js'

(running it on a mac)

**Comment by joshpitzalis** [comment]
seems to work on Claire' machine so don't mind me.
